services:
  langflow:
    image: langflowai/langflow:latest
    profiles: ["agent_builders"]
    ports:
      - "${AI_BEAST_BIND_ADDR:-127.0.0.1}:${PORT_LANGFLOW:-7860}:7860"
    environment:
      - LANGFLOW_HOST=0.0.0.0
      - LANGFLOW_PORT=7860
    volumes:
      - "${DATA_DIR:-./data}/langflow:/data"
    restart: unless-stopped
