# Qdrant vector database for RAG workflows
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: ai_beast_qdrant
    profiles: ["qdrant", "full", "prodish"]
    ports:
      - "${AI_BEAST_BIND_ADDR:-127.0.0.1}:${PORT_QDRANT:-6333}:6333"
      - "${AI_BEAST_BIND_ADDR:-127.0.0.1}:${PORT_QDRANT_GRPC:-6334}:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      QDRANT__SERVICE__GRPC_PORT: "6334"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/readyz"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  qdrant_data:
