#!/usr/bin/env bash
set -euo pipefail

APPLY=0
for arg in "${@:-}"; do
  [[ "$arg" == "--apply" ]] && APPLY=1
done

log(){ echo "[init] $*"; }
die(){ echo "[init] ERROR: $*" >&2; exit 1; }

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$script_dir/.." && pwd)"

default_external_volume() {
  ls -1 /Volumes 2>/dev/null | grep -vE '^(Macintosh HD|Macintosh HD - Data|Recovery|Preboot|VM)$' | head -n 1 || true
}

prompt_path() {
  local label="$1" def="$2" ans=""
  printf "%s
Default: %s
Enter path (or press Return): " "$label" "$def"
  IFS= read -r ans || true
  [[ -n "${ans:-}" ]] && echo "$ans" || echo "$def"
}

ensure_dir(){
  local p="$1"
  if [[ "$APPLY" -ne 1 ]]; then
    log "DRYRUN: would mkdir -p "$p""
  else
    mkdir -p "$p"
  fi
}

write_paths_env(){
  local out="$1"
  if [[ "$APPLY" -ne 1 ]]; then
    log "DRYRUN: would write $out"
    return 0
  fi
  cat > "$out" <<EOF
# Generated by ./bin/beast init on $(date)
# shellcheck disable=SC2034

# Project root (guts). Keep on internal SSD.
export BASE_DIR="$PROJECT_ROOT"
export GUTS_DIR="$GUTS_DIR"

# Heavy storage (models/data/outputs). Prefer external SSD.
export HEAVY_DIR="$HEAVY_DIR"

export MODELS_DIR="$MODELS_DIR"
export DATA_DIR="$DATA_DIR"
export OUTPUTS_DIR="$OUTPUTS_DIR"
export CACHE_DIR="$CACHE_DIR"
export BACKUP_DIR="$BACKUP_DIR"
export LOG_DIR="$LOG_DIR"

# Optional subroots
export COMFYUI_MODELS_DIR="$COMFYUI_MODELS_DIR"
export LLM_MODELS_DIR="$LLM_MODELS_DIR"

# Native guts locations
export COMFYUI_DIR="$COMFYUI_DIR"
export VENV_DIR="$VENV_DIR"
EOF
  log "Wrote: $out"
}

main(){
  log "Project root (guts): $PROJECT_ROOT"

  local ext_vol; ext_vol="$(default_external_volume)"
  local default_guts="$PROJECT_ROOT"
  local default_heavy
  if [[ -n "$ext_vol" ]]; then
    default_heavy="/Volumes/$ext_vol/AI_Beast_Heavy"
  else
    default_heavy="$PROJECT_ROOT"
  fi

  GUTS_DIR="$(prompt_path "Where should native apps/venv live? (guts)" "$default_guts")"
  HEAVY_DIR="$(prompt_path "Where should models/data/outputs live? (heavy)" "$default_heavy")"

  MODELS_DIR="$HEAVY_DIR/models"
  DATA_DIR="$HEAVY_DIR/data"
  OUTPUTS_DIR="$HEAVY_DIR/outputs"
  CACHE_DIR="$HEAVY_DIR/cache"
  BACKUP_DIR="$HEAVY_DIR/backups"
  LOG_DIR="$HEAVY_DIR/logs"

  COMFYUI_MODELS_DIR="$MODELS_DIR/comfyui"
  LLM_MODELS_DIR="$MODELS_DIR/llm"

  COMFYUI_DIR="$GUTS_DIR/apps/comfyui/ComfyUI"
  VENV_DIR="$GUTS_DIR/.venv"

  # Create dirs (best-effort)
  ensure_dir "$HEAVY_DIR"
  for d in "$MODELS_DIR" "$DATA_DIR" "$OUTPUTS_DIR" "$CACHE_DIR" "$BACKUP_DIR" "$LOG_DIR"; do
    ensure_dir "$d"
  done
  for d in checkpoints loras vae controlnet embeddings upscale_models clip clip_vision; do
    ensure_dir "$COMFYUI_MODELS_DIR/$d"
  done

  ensure_dir "$PROJECT_ROOT/config"

  write_paths_env "$PROJECT_ROOT/config/paths.env"
  # Copy ports/profiles templates if missing
  if [[ "$APPLY" -eq 1 ]]; then
    [[ -f "$PROJECT_ROOT/config/ports.env" ]] || cp -n "$PROJECT_ROOT/config/ports.env.example" "$PROJECT_ROOT/config/ports.env" || true
    [[ -f "$PROJECT_ROOT/config/profiles.env" ]] || cp -n "$PROJECT_ROOT/config/profiles.env.example" "$PROJECT_ROOT/config/profiles.env" || true
    [[ -f "$PROJECT_ROOT/config/ai-beast.env" ]] || cp -n "$PROJECT_ROOT/config/ai-beast.env.example" "$PROJECT_ROOT/config/ai-beast.env" || true
  else
    log "DRYRUN: would ensure config/ports.env + config/profiles.env + config/ai-beast.env exist"
  fi

  log "Next:"
  echo "  $PROJECT_ROOT/bin/beast features sync --apply"
  echo "  $PROJECT_ROOT/bin/beast preflight"
  echo "  $PROJECT_ROOT/bin/beast bootstrap --dry-run"
  echo "  $PROJECT_ROOT/bin/beast bootstrap --apply"
}

main "$@"
