name: build
phases:
  - role: supervisor
    prompt: apps/agent/prompts/kryptos_builder.supervisor.md
  - role: implementer
    prompt: apps/agent/prompts/kryptos_builder.system.md
    tool_loop: true
  - role: verifier
    prompt: apps/agent/prompts/kryptos_builder.verifier.md
    tool_loop: true
